"""empty message

Revision ID: 339ba1d32cfb
Revises: 
Create Date: 2021-04-24 00:29:01.556750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339ba1d32cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_user')
    op.drop_table('task')
    # ### end Alembic commands ###
